[WIP] bootstrap app
pmsipilot/calendar-board pull request #1
Opened 2016-12-28 15:27 UTC by kevinbalicot

Application qui permet d'avoir le calendrier des salles 

Vue sous forme de liste : 
![capture d ecran 2016-12-28 a 16 16 47_censored](https://cloud.githubusercontent.com/assets/4362142/21524968/3cca2540-cd1a-11e6-8609-e4d5fe4e5ed2.jpg)

Vue sous forme de tableau : 
![capture d ecran 2016-12-28 a 16 16 54_censored](https://cloud.githubusercontent.com/assets/4362142/21524974/4ad8c4f2-cd1a-11e6-8ac4-b992cfcb537c.jpg)

2016-12-28 16:32 UTC, wixyvir commented on Makefile
> +	./node_modules/.bin/browserify index.js -o $(BIN_FILE) -t [ babelify ]
Je trouve qu'il est mieux, lorsqu'il s'agit de faire des appels à des binaires présents dans `node_modules`, de passer par un script de `package.json`, afin de profiter du `PATH` modifié de npm. Cela est utile, si un jour lors d'une mise à jour, l'emplacement du binaire est modifié (ici par le paquet browserify).

2016-12-28 16:32 UTC, wixyvir commented on package.json
>    "description": "Calendar board for PMSIpilot organisation",
Sauf s'il on compte publier directement le module, peut être ajouter `"private": true`?

2016-12-28 16:32 UTC, wixyvir commented on src/components/board.js
> +        this.hours = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19];
Pour ne pas en oublier, peut être définir le tableau grâce à un range? Comme la http://stackoverflow.com/questions/3746725/create-a-javascript-array-containing-1-n

2016-12-28 16:32 UTC, wixyvir commented on src/config/key.dist.json
> +        "client_secret":"o0-d-7RszmzDxFh2F7F2qnlP",
:open_mouth:

2016-12-28 16:38 UTC, kevinbalicot commented on src/config/key.dist.json
> +        "client_secret":"o0-d-7RszmzDxFh2F7F2qnlP",
:O

2016-12-28 22:13 UTC, jubianchi commented on package.json
>    "description": "Calendar board for PMSIpilot organisation",
dans tous les cas, le `"private": true` devrait être ajouté : c'est une application, pas un module donc aucune raison de la publier sur NPM.

Par contre, en effet, la description devrait peut-être être du genre `Calendar board for Google Apps organisations`

2016-12-28 22:23 UTC, jubianchi requested changes

2016-12-28 22:23 UTC, jubianchi commented on Makefile
> +	./node_modules/.bin/browserify index.js -o $(BIN_FILE) -t [ babelify ]
@wixyvir utiliser `make` pour lancer une tâche NPM me semble inutile : soit on utilise NPM soit `make`, mais pas l'un dans l'autre.

Ensuite, si le path vers `browserify` change, c'est que le module lui même change de nom, et là, pour le coup c'est un BC break de Browserify qui impliquera forcément une mise à jour plus profonde de notre application donc du script NPM ou de la recette `make`.

2016-12-28 22:23 UTC, jubianchi commented on Makefile
> +BIN_DIR = ./dist
`./dist` n'est pas vraiment un dossier de binaires... j'aurais plutôt nommé la variable `DIST_DIR` pour être clair et éviter les confusions.

2016-12-28 22:23 UTC, jubianchi commented on Makefile
> +BIN_DIR = ./dist
`BIN_DIR` serait plutôt `./node_modules/.bin` pour moi.

2016-12-28 22:23 UTC, jubianchi commented on .babelrc
> +{
de mémoire, la config `babel` peut-être mergée dans le `package.json` : je trouve ça plus clean, ça évite la multiplication des fichiers de config à la racine du dépôt.

2016-12-28 22:23 UTC, jubianchi commented on Makefile
> +$(BIN_FILE): node_modules
pas de recette ici ? pourtant, le `app.js` est généré par le lancement de `browserify` : pour moi, la recette de la cible `build` devrait se trouver ici, et `build` ne serait qu'un alias de `$(BIN_FILE)`

2016-12-28 22:23 UTC, jubianchi commented on README.md
> +Il faut également ajouter une clé OAuth de type `Web application` générée via la console de Google (à mettre dans `src/config`)
placer la le fichier de config doit être fait avant le `make`, non ?

2016-12-28 22:23 UTC, jubianchi commented on index.html
> +        <title>PMSIpilot calendrier</title>
`PMSIpilot Calendar Board` ?

2016-12-28 22:23 UTC, jubianchi commented on index.js
> +    console.log('bootstrap');
oups :)

2016-12-28 22:23 UTC, jubianchi commented on index.js
> +// Need to bootstrap angular app after gapi is loaded
est-ce que ce commentaire est juste/pertinent ? je ne vois pas où est chargé `gapi` ici :)

2016-12-29 07:12 UTC, kevinbalicot commented on package.json
>    "description": "Calendar board for PMSIpilot organisation",
L'app n'est pas assez global pour prétendre être une "Calendar board for Google Apps organisations", je dois virer tous les appels à nos id de calendrier et ajouter ça dans une configuration

2016-12-29 07:14 UTC, kevinbalicot commented on src/components/board.js
> +        this.hours = [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19];
J'en étais sur que quelqu'un allait me faire la remarque, à part pour une notion de config, je vois pas l’intérêt. Entre faire tout un truc pour générer un tableau et définir en dur le tableau je trouve le deuxième choix moins ambigüe et plus simple :) (bon je vais quand même faire le range pour pouvoir configurer les heures)

2016-12-29 07:23 UTC, kevinbalicot commented on README.md
> +Il faut également ajouter une clé OAuth de type `Web application` générée via la console de Google (à mettre dans `src/config`)
ah bah oui ...

2016-12-29 07:24 UTC, kevinbalicot commented on index.js
> +// Need to bootstrap angular app after gapi is loaded
Ahaha il est bien caché :p (regardes dans index.html, l'appel à la lib gapi) En fait c'est surtout pour expliquer pourquoi l'appel `platformBrowserDynamic` est encapsulé dans une fonction. Peut être ajouter plus d'explication dans le commentaire

2016-12-29 07:32 UTC, kevinbalicot commented on .babelrc
> +{
+1

2016-12-30 10:53 UTC, jubianchi approved these changes

2016-12-30 13:46 UTC, merged