Use envify to expand env. variables during build
pmsipilot/calendar-board pull request #7
Opened 2017-01-04 09:56 UTC by jubianchi

2017-01-04 10:04 UTC, wixyvir requested changes

2017-01-04 10:04 UTC, wixyvir commented on Makefile
> +recurse=$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call recurse,$d/,$2))
Je trouve cette syntaxe complètement illisible pour des novices. Je pense qu'il est bien plus simple de faire un `JS_NODE=$(find node_modules/ -type f -iname '*.js')`

2017-01-04 10:04 UTC, wixyvir commented on config/config.js
> +    calendars: process.env.CALENDARBOARD_CALENDARS ? process.env.CALENDARBOARD_CALENDARS.split(',') : [
Il faut donc ajouter ça dans `Dockerfile` et `docker-compose.yml` je peux m'en occuper si tu veux.

2017-01-04 10:14 UTC, jubianchi commented on Makefile
> +recurse=$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call recurse,$d/,$2))
@wixyvir `find` n'est pas portable.

2017-01-04 10:14 UTC, jubianchi commented on config/config.js
> +    calendars: process.env.CALENDARBOARD_CALENDARS ? process.env.CALENDARBOARD_CALENDARS.split(',') : [
je m'en charge

2017-01-04 10:15 UTC, jubianchi commented on config/config.js
> +    calendars: process.env.CALENDARBOARD_CALENDARS ? process.env.CALENDARBOARD_CALENDARS.split(',') : [
en fait, ce n'est pas indispensable de les ajouter : par défaut, un calendrier générique est afficher si la variable n'est pas renseignée.

J'ai documenté la variable dans le readme, je pense que c'est suffisant.

2017-01-04 10:35 UTC, wixyvir commented on Makefile
> +recurse=$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call recurse,$d/,$2))
Toutes les options de find ne sont pas portables effectivement. `type`et `name` semblent l'être d'après le man et des ressources sur le web comme http://www.in-ulm.de/~mascheck/various/find/.

Je trouve que la portabilité de findutils sort de ce qu'on pourrait définir comme un "périmètre de préoccupation" pour ce projet, ce sera plutot difficile de trouver un système ou tout tes scripts nodes fonctionneront sans erreurs, alors que cette implémentation très basique de find non.

A voir, c'est ici peut être une différence de point de vue mais je trouve que c'est mieux lorsque le code est lisible par les développeurs. Si il y a une erreur avec find, au moins, un néophyte comprendra. Avec ta définition de wildcard je suis pas sur.

2017-01-04 10:38 UTC, wixyvir approved these changes

2017-01-04 10:54 UTC, jubianchi commented on Makefile
> +recurse=$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call recurse,$d/,$2))
@wixyvir je vais appliquer le changement et passer sur `find` parce que je comprends l'argument "c'est mieux lorsque le code est lisible par les développeurs" même si je ne suis pas d'accord car :

* `find` n'est pas portable (je me répète) : que se passe-t-il si un contributeur Windows arrive sur le projet. Ici, ce n'est pas un code privé, on ne maîtrise pas l'environnement de _tous_ les contributeurs potentiels,
* les macros `make` sont standards, documentées, un développeur doit savoir se documenter s'il ne comprends pas ce qu'il lit

2017-01-04 12:26 UTC, kevinbalicot approved these changes

2017-01-04 12:26 UTC, kevinbalicot commented on package.json
> -      "presets": ["es2015", "angular2"]
pourquoi ce changement ?

2017-01-04 12:30 UTC, merged

2017-01-04 13:22 UTC, jubianchi commented on package.json
> -      "presets": ["es2015", "angular2"]
@kevinbalicot j'ai fait un `npm install --save-dev` et le fichier a été auto-réindenté par `npm` avec ses propres conventions. 

J'ai laissé comme il l'avait mis parce que sinon, à chaque ajout d'une nouvelle dépendance on va retrouver ce diff là.

2017-01-05 09:41 UTC, kevinbalicot commented on package.json
> -      "presets": ["es2015", "angular2"]
:+1: